import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/next';
import { Playfair_Display, Inter } from 'next/font/google';
import { site } from '@/config/site';
import { SiteSchema } from '@/components/site-schema';
import Footer from '@/components/footer';
import './globals.css';

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-playfair-display',
});
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: site.ogTitle,
  description: site.description,
  // SVG favicon is primary — it embeds the logomark with a prefers-color-scheme
  // media query inside the SVG itself, which is how Chrome actually switches icons.
  // PNG fallbacks are kept for browsers that don't support SVG favicons (Safari).
  // Generated by /assets -- re-run if the logomark changes.
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icon-light.png', media: '(prefers-color-scheme: light)' },
      { url: '/icon-dark.png', media: '(prefers-color-scheme: dark)' },
    ],
  },
  openGraph: {
    title: site.ogTitle,
    description: site.ogDescription ?? site.description,
    url: site.url,
    siteName: site.name,
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    site: site.social?.twitterHandle,
    title: site.ogTitle,
    description: site.ogDescription ?? site.description,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${playfair.variable} ${inter.variable}`}>
      <body className="font-body antialiased">
        <SiteSchema />
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
